services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      ALLOW_ORIGIN: ${ALLOW_ORIGIN}
      JWT_TOKEN_EXPIRATION: ${JWT_TOKEN_EXPIRATION}
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    command: sleep infinity

  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    environment:
      VITE_API_URL: ${VITE_API_URL}
    command: sleep infinity
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace